#!/bin/bash

# Create htpasswd
if [ ! -e ${NAGIOS_HOME}/etc/htpasswd.users ]; then
    htpasswd -c -b -s ${NAGIOS_HOME}/etc/htpasswd.users ${NAGIOSADMIN_USER} ${NAGIOSADMIN_PASS}
    chown -R nagios.nagios ${NAGIOS_HOME}/etc/htpasswd.users
fi

# Fixup nagios apache config
sed -i \
    "s|%%APACHE_VHOST_SERVERNAME%%|${APACHE_VHOST_SERVERNAME}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_SERVERADMIN%%|${APACHE_VHOST_SERVERADMIN}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_PORT%%|${APACHE_VHOST_PORT}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_USESSL%%|${APACHE_VHOST_USESSL}|" \
    /etc/apache2/sites-available/nagios.conf
a2ensite -q nagios

# Mailserver
if [ -z $MAIL_SERVER ]; then
    if [ ! -z $MAIL_VARIABLE ]; then
        eval MAIL_SERVER=\${$MAIL_VARIABLE}
    fi
fi
if [ -n $MAIL_SERVER ]; then
    sed -i "s/relayhost =.*/relayhost = ${MAIL_SERVER}/" /etc/postfix/main.cf
    sed -i "s/myhostname =.*/myhostname = `hostname`/" /etc/postfix/main.cf
    /etc/init.d/postfix start
fi
