#!/bin/bash

# Set timezone
echo ${SYSTEM_TIMEZONE} > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

# Create htpasswd
htpasswd -c -b -s ${NAGIOS_HOME}/etc/htpasswd.users ${NAGIOSADMIN_USER} ${NAGIOSADMIN_PASS}
chown -R nagios.nagios ${NAGIOS_HOME}/etc/htpasswd.users

# Fixup nagios apache config
sed -i \
    "s|%%APACHE_VHOST_SERVERNAME%%|${APACHE_VHOST_SERVERNAME}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_SERVERADMIN%%|${APACHE_VHOST_SERVERADMIN}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_PORT%%|${APACHE_VHOST_PORT}|" \
    /etc/apache2/sites-available/nagios.conf
sed -i \
    "s|%%APACHE_VHOST_USESSL%%|${APACHE_VHOST_USESSL}|" \
    /etc/apache2/sites-available/nagios.conf
a2ensite nagios
